services: 
  postgres-prisma:
    image: postgres:15
    container_name: postgres_prisma
    restart: always
    ports: 
      - "9999:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: sandbox_prisma_db
    volumes:
      - test-prisma-data:/var/lib/postgresql/data

  postgres-typeorm:
    image: postgres:15
    container_name: postgres_typeorm
    restart: always
    ports: 
      - "9988:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: sandbox_typeorm_db
    volumes:
      - test-typeorm-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sandbox_redis
    restart: always
    ports: 
      - "6229:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  test-prisma-data:
  test-typeorm-data:
  redis-data: